In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("D:/Senior Project/Mallorn version 2/Data/Actual Mallorn data/split_01/test_full_lightcurves.csv")
df.head()

         object_id  Time (MJD)      Flux  Flux_err Filter
0  Elrim_sador_hun  61120.3730 -0.867298  1.436325      z
1  Elrim_sador_hun  62428.9395 -0.412872  0.972737      y
2  Elrim_sador_hun  62431.2074  0.807585  0.421561      i
3  Elrim_sador_hun  62431.2074  0.564190  0.702448      z
4  Elrim_sador_hun  62444.8147  0.495302  0.135575      r

In [ ]:
df1 = pd.read_csv("D:/Senior Project/Mallorn version 2/Data/Porcessed Data/CNN_split/train_df.csv")
df1.drop(columns=["object_id", "Time (MJD)", "SpecType", "Filter_g_flux_err", "Filter_g_flux"], inplace=True)
df1.head()

,Filter_z_flux,Filter_z_flux_err,Filter_r_flux,Filter_r_flux_err,Filter_y_flux,Filter_y_flux_err,Filter_i_flux,Filter_i_flux_err,Filter_u_flux,Filter_u_flux_err
0,-1.895487,0.425312,0.000000,0.000000,-1.601633,1.191244,0.000000,0.000000,0.0,0.0
1,-1.811662,0.462278,0.000000,0.000000,0.000000,0.000000,-1.709337,0.389580,0.0,0.0
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-2.495971,0.403594,0.0,0.0
3,0.000000,0.000000,-1.328391,0.225768,0.000000,0.000000,0.000000,0.000000,0.0,0.0
4,0.000000,0.000000,-1.396016,0.576872,0.000000,0.000000,0.000000,0.000000,0.0,0.0

In [19]:
before = np.linspace(0,10,10, dtype=int)
rng = np.random.default_rng(40)
after = before + rng.normal(0, 0.05 * np.abs(before), size=len(before))
print(before, "\n", np.round(after,2))

[ 0  1  2  3  4  5  6  7  8 10]
 [0.   0.95 1.92 3.12 3.79 4.74 5.88 7.49 7.63 9.65]

In [ ]:
print(f"{'Before':>6} | {'After':>8}")
print("-" * 17)
for b, a in zip(before, after):
    print(f"{b:6d} | {a:8.2f}")

Before |    After
-----------------
     0 |     0.00
     1 |     0.95
     2 |     1.92
     3 |     3.12
     4 |     3.79
     5 |     4.74
     6 |     5.88
     7 |     7.49
     8 |     7.63
    10 |     9.65

: